config/routes.rb
Rails.application.routes.draw do
  resources :view_messages
  resources :homes

  root 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :message, presence: true
end

app/models/view_message.rb
class ViewMessage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  def index
    @homes = Home.all
  end

  def show
    @home = Home.find(params[:id])
    @homes = Home.order('created_at desc').limit(4).offset(1)
  end

  def new
    @home = Home.new
  end

  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html do
          flash[:success] = 'Message Sent!'
          redirect_to homes_url
        end
      else
        format.html { flash[:failure!] = 'Message Not Sent! Verify Details & Send Again!' }
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to view_messages_url, notice: 'Contact was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_home
      @home = Home.find(params[:id])
    end

    def home_params
      params.require(:home).permit(:name, :email, :message)
    end
end

app/controllers/view_messages_controller.rb
class ViewMessagesController < ApplicationController
  before_action :set_view_message, only: [:show, :edit, :update, :destroy]

  def index
    @view_messages = ViewMessage.all
    @homes = Home.all
  end

  def show
    @view_message = ViewMessage.find(params[:id])
    @view_messages = ViewMessage.order('created_at desc').limit(4).offset(1)
  end

  def new
    @view_message = ViewMessage.new
  end

  def create
    @view_message = ViewMessage.new(view_message_params)

    respond_to do |format|
      if @view_message.save
        format.html do
          flash[:success] = 'Messages Seen!'
          redirect_to homes_url
        end
      else
        format.html { flash[:failure!] = 'Messages Not Seen! Verify Details & Send Again!' }
        format.html { render 'new' }
      end
    end
  end

  def destroy
    @view_message.destroy
    respond_to do |format|
      format.html { redirect_to view_messages_url, notice: 'Message was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_view_message
      @view_message = ViewMessage.find(params[:id])
    end

    def view_message_params
      params.fetch(:view_message, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/view_messages_helper.rb
module ViewMessagesHelper
end

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<!-- Content -->
<div class="w3-content" style="max-width:1100px;margin-top:80px;margin-bottom:80px">

  <div class="w3-panel">
    <div class="w3-col l4 m6">
      <img src="assets/logo.png" class="w3-image">
    </div>
  </div>

  <!-- Slideshow -->
  <div class="w3-container">
    <div class="w3-display-container mySlides w3-animate-fading">
      <img src="assets/homePic3.jpg" style="width:100%">
      <div class="w3-display-topleft w3-container w3-padding-32">
        <span class="w3-white w3-padding-large w3-animate-bottom">Project Management</span>
      </div>
    </div>
    <div class="w3-display-container mySlides w3-animate-fading">
      <img src="assets/homePic1.jpg" style="width:100%">
      <div class="w3-display-middle w3-container w3-padding-32">
        <span class="w3-white w3-padding-large w3-animate-bottom">Business</span>
      </div>
    </div>
    <div class="w3-display-container mySlides w3-animate-fading">
      <img src="assets/homePic2.jpg" style="width:100%">
      <div class="w3-display-topright w3-container w3-padding-32">
        <span class="w3-white w3-padding-large w3-animate-bottom">International Business</span>
      </div>
    </div>

    <!-- indigo bar below slider -->
    <div class="w3-container w3-indigo w3-padding w3-xlarge">
      <div class="w3-center">
        <a href="#footer" class="w3-bar-item w3-button w3-hover-white" title="Go Down"><h3><i class="fa fa-chevron-circle-down"></i></h3></a>
      </div>
    </div>
  </div>
  
  <!-- Our Services -->
  <div class="w3-row w3-container" id="services">
    <div class="w3-right w3-padding-64">
      <span class="w3-xlarge w3-bottombar w3-border-indigo w3-padding-16">What We Offer</span>
    </div>

    <div class="w3-margin-bottom">
      <img class="w3-image w3-opacity" src="assets/servicesBanner.jpg" alt="servicesImage">
    </div>

    <div class="w3-col l3 m6 w3-light-grey w3-container w3-padding-16">
      <h3><b>Project<br> management</b></h3>
      <p>We give detailed information on project management and the various tools.</p>
    </div>

    <div class="w3-col l3 m6 w3-grey w3-container w3-padding-16">
      <h3><b>Business<br> management</b></h3>
      <p>We educate and train interested parties concerning business managemant.</p>
    </div>

    <div class="w3-col l3 m6 w3-dark-grey w3-container w3-padding-16">
      <h3><b>Leadership<br></b></h3>
      <p> ->Training & <br> ->Open forums <br> ->Bootcamps <br> On matters concerning leadership.</p>
    </div>

    <div class="w3-col l3 m6 w3-color w3-container w3-padding-16 w3-color-text">
      <h3><b>International<br> Business</b></h3>
      <p>We provide consultations that deals on topics about International business.</p>
    </div>
  </div>

  <!-- About Us Section -->
  <div class="w3-container w3-padding-64 w3-theme-l5" id="about">
    <div class="w3-left w3-padding-64">
      <span class="w3-xlarge w3-bottombar w3-border-indigo w3-padding-16">About Us</span>
    </div>

    <div class="w3-margin-bottom">
      <img class="w3-image w3-opacity" src="assets/banner.jpg" alt="aboutusImage">
    </div>

    <div class="w3-row">
      <div class="w3-col m5">
        <div class="w3-margin-bottom">
          <div class="w3-card-4">
            <div class="w3-container">
              <h3>Jack</h3>
              <p class="w3-opacity">CEO & Founder</p>
              <p>Qualifications.</p>
              <p><button class="w3-button w3-light-grey w3-block">Contact</button></p>
            </div>
          </div>
        </div>
      </div>

      <div class="w3-col m7 w3-padding-large">
        <h3>About Mumus Training & Consulting.</h3>
        <p>Mumus Training and consulting is a Training and Consoltation platform.<br> The fields of interest are:<br> ->Project Management.<br> ->Business Administration.<br> ->Leadership &<br> ->International Business.</p>
      </div>
    </div>
  </div>

  <!-- Contact Container -->
  <div class="w3-container w3-padding-64 w3-theme-l5" id="contact">

    <div class="w3-padding-16 w3-right"><span class="w3-xlarge w3-border-indigo w3-bottombar">Contact Us</span></div>

    <div class="w3-margin-bottom">
      <img class="w3-image w3-opacity" src="assets/contactBanner.png" alt="contactImage">
    </div>

    <div class="w3-row">
      <div class="w3-col m5">
        <h3>Address</h3>
        <p><i class="fa fa-map-marker w3-text-indigo w3-xlarge"></i>  Nairobi, Kenya</p>
        <p><i class="fa fa-phone w3-text-indigo w3-xlarge"></i>  +254 723763766</p>
        <p><i class="fa fa-envelope-o w3-text-indigo w3-xlarge"></i>  consultancy@mumustraining.com</p>
      </div>
      <div class="w3-col m7">

        <%= form_for Home.new, url: {action: "create"}, html: {class: "w3-container w3-card-4 w3-padding-16 w3-white"} do |f| %>
          <div class="w3-section">      
            <label class="w3-text-indigo">Name</label>
            <%= f.text_field :name, class: 'w3-input'%>
          </div>
          <div class="w3-section">      
            <label class="w3-text-indigo">Email</label>
            <%= f.text_field :email, class: 'w3-input'%>
          </div>
          <div class="w3-section">      
            <label class="w3-text-indigo">Message</label>
            <%= f.text_field :message, class: 'w3-input'%>
          </div>  
          <button type="submit" class="w3-button w3-indigo w3-right w3-theme fa fa-paper-plane"> Send</button>
        <% end %>

        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>

      </div>
    </div>


  </div>

</div>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @home.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @home.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @home.message %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MuMus Training & Consulting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Font Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- W3.css -->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    
    <!-- COUSTOM CSS link  -->
    <link rel="stylesheet" href="assets/stylesheets/css/style.css">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FAV AND ICONS   -->
    <link rel="icon" type="image/ico" href="assets/favicon.png" sizes="32x32" />

    <!-- Google fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato"> 
    
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/alerts' %>
      <%= yield %>
    <%= render 'shared/footer' %>

    <script>
      carousel();
    </script>
  </body>

</html>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="w3-container w3-padding-32 w3-theme-d1 w3-center w3-light-grey" id="footer">
  <h4>Follow Us</h4>
  <a class="w3-button w3-large w3-indigo w3-hover-dark-grey" href="javascript:void(0)" title="Facebook"><i class="fa fa-facebook w3-color-text"></i></a>
  <a class="w3-button w3-large w3-indigo w3-hover-dark-grey" href="javascript:void(0)" title="Twitter"><i class="fa fa-twitter w3-color-text"></i></a>
  <a class="w3-button w3-large w3-indigo w3-hover-dark-grey" href="javascript:void(0)" title="Linkedin"><i class="fa fa-linkedin w3-color-text"></i></a>
  <p><i>Copyright &copy; 2019 Mumus Training & Consulting -All Rights Reserved.</i></p>

  <div style="position:relative;bottom:100px;z-index:1;" class="w3-tooltip w3-right">
    <span class="w3-text w3-padding w3-color w3-hide-small w3-color-text">Go To Top</span>   
    <a class="w3-button w3-theme" href="#"><span class="w3-xlarge">
    <i class="fa fa-chevron-circle-up"></i></span></a>
  </div>

  <div style="position:relative;bottom:100px;z-index:1;" class="w3-tooltip w3-left w3-hide-small"> 
    <button onclick="myFunction()" class="w3-button w3-grey w3-theme fa fa-envelope"> View Messages</button> 
    <p id="demo"></p>
  </div>

</footer>

<!-- script -->
<script src="assets/javascripts/js/main.js"></script>

app/views/shared/_header.html.erb
<!-- Links (sit on top) -->
<div class="w3-top">
  <div class="w3-row w3-color">
    <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-hover-indigo w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><h5><b><i class="fa fa-bars w3-color-text"></i></b></h5></a>

    <div class="w3-col s3">
      <a href="homes" class="w3-button w3-block w3-hover-indigo"><h5 class="w3-color-text"><b><i>Home</i></b></h5></a>
    </div>
    <div class="w3-col s3">
      <a href="#services" class="w3-button w3-block w3-hide-small w3-hover-indigo"><h5 class="w3-color-text"><b><i>Services</i></b></h5></a>
    </div>
    <div class="w3-col s3">
      <a href="#about" class="w3-button w3-block w3-hide-small w3-hover-indigo"><h5 class="w3-color-text"><b><i>About</i></b></h5></a>
    </div>
    <div class="w3-col s3">
      <a href="#contact" class="w3-button w3-block w3-hide-small w3-hover-indigo"><h5 class="w3-color-text"><b><i>Contact</i></b></h5></a>
    </div>
  </div>

  <div style="width:12%" class="w3-panel-2 w3-right w3-hide-small w3-padding-16">
    <input type="text" id="myInput" onkeyup="searchFunction()" placeholder="Search" title="Type in a name" class="w3-hover-light-grey w3-round-xlarge  w3-input">
  </div>

  <!-- Links on small screens -->
  <div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium w3-indigo">
    <a href="#services" class="w3-bar-item w3-button w3-hover-light-grey"><b><i>Services</i></b></a>
    <a href="#about" class="w3-bar-item w3-button w3-hover-light-grey"><b><i>About</i></b></a>
    <a href="#contact" class="w3-bar-item w3-button w3-hover-light-grey"><b><i>Contact</i></b></a>
    <input type="text" id="myInput" onkeyup="searchFunction()" placeholder="Search" title="Type in a name"> 
  </div>
</div>

app/views/view_messages/_form.html.erb
<%= form_with(model: view_message, local: true) do |form| %>
  <% if view_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(view_message.errors.count, "error") %> prohibited this view_message from being saved:</h2>

      <ul>
      <% view_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/view_messages/edit.html.erb
<h1>Editing View Message</h1>

<%= render 'form', view_message: @view_message %>

<%= link_to 'Show', @view_message %> |
<%= link_to 'Back', view_messages_path %>

app/views/view_messages/index.html.erb
<!-- Content -->
<div class="w3-content" style="max-width:1100px;margin-top:80px;margin-bottom:80px">

  <div class="w3-panel">
    <div class="w3-col l4 m6">
      <img src="assets/logo.png" class="w3-image">
    </div>
  </div>

  <!-- Table Section -->
  <table class="w3-table w3-bordered w3-striped w3-border test w3-hoverable">
    <tr class="w3-indigo">
      <th>Name</th>
      <th>Email</th>
      <th>Message</th>
      <th class="w3-hide-small">Delete</th>
    </tr>
    <tbody>
      <% @homes.each do |home| %>
        <tr>
          <td><%= home.name %></td>
          <td><%= home.email %></td>
          <td><%= home.message %></td>
          <td class="w3-hide-small">
            <%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr> 
      <% end %>
    </tbody>
  </table>

</div>

app/views/view_messages/new.html.erb
<h1>New View Message</h1>

<%= render 'form', view_message: @view_message %>

<%= link_to 'Back', view_messages_path %>

app/views/view_messages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_view_message_path(@view_message) %> |
<%= link_to 'Back', view_messages_path %>